import os, sys
sys.path.insert(0,os.getcwd() )

from toolbox.calculate_rewards import calculate_rewards
from toolbox.generate_retry import generate_retry
from utils.clear_cache import clear_cache

import json
import torch
	

def rl_trainer(trainer, reward_model, tokenizer, batch, args, generation_kwargs, device_map="auto" ):	
		
	batch["response"] = []
	response_tensors = []
	rewards = []

	stats= None
	loss= None
	kl= None
		
	#### Phase 1: Generate responses to queries
	response_tensors= generate_retry(trainer.model, tokenizer, batch, generation_kwargs)
	if response_tensors is None:
		print("No response was generated by the model for at least one of the inputs. Let's pass to next batch of questions")
		return stats, loss, kl	
		
	batch["response"]=[tokenizer.decode(response, skip_special_tokens=True) for response in response_tensors]	
	# debug
	print("\nResponses for this batch:\n")
	for j in range(len(batch["response"])):
		print(j)
		print(batch["response"][j])
		print("")		
    
	#### Phase 2: Compute rewards for the entire batch in one go
	print("Calculate rewards")
	# Texts shall conform with reward modeling's inputs: post-processing is needed. This is performed later
	texts = [query + response for query, response in zip(batch["query"], batch["response"])]
	# debug
	#print('Original prompt:')
	#print(texts[0])
    
	# Compute the rewards after post-processing tests
	logits = calculate_rewards(reward_model, 
		tokenizer, 
		tuple(texts), 
		args.padding, 
		max_len= args.cutoff_len if args.max_len_rm is None else min(args.cutoff_len, args.max_len_rm), # to conform to the answers in the data set
		pad_to_multiple_of= args.pad_to_multiple_of,
		)
	calculate_rewards.cache_clear() #to freed cpu cache
	clear_cache()
			
	trainer_device = trainer.accelerator.device
	reward_tensors = [torch.tensor(logit.item(), device=trainer_device) for logit in logits] 
	print(reward_tensors)
	del logits
	clear_cache()

	#### Phase 3: Calculate the logprobs and then run the PPO update		
	# Move tensor to trainer's device
	response_tensors = [r.to(trainer_device) for r in response_tensors]  
	input_ids_tensors = [r.squeeze().to(trainer_device) for r in batch["input_ids"]] # squeeze() to conform shape		
	#break
		
	print("Let's update the model")  
	stats = trainer.step(queries=input_ids_tensors, responses=response_tensors,scores=reward_tensors) 
	print("Step performed")
	clear_cache()
	#trainer.log_stats(stats, batch, rewards)  # Log to external tool
	#break
	if 'ppo/loss/value' in stats:
		loss= stats['ppo/loss/value'] 		
	if 'objective/kl' in stats:
		kl= stats['objective/kl']    		
	
	return stats, loss, kl
