import os, sys
sys.path.insert(0,os.getcwd() )

from toolbox.calculate_rewards import calculate_rewards
from toolbox.generate_retry import generate_retry
from toolbox.miscellaneous import create_prompt
from utils.clear_cache import clear_cache
from utils.prompts import FAULT_ANSWER

import openai
import os
from tenacity import (
	retry,
	stop_after_attempt, # type: ignore
	wait_random_exponential, # type: ignore
	)
# from fastchat.model import get_conversation_template
import torch


class OpenAILLM(object):
	def __init__(self, model, generation_kwargs=None):
		self.model = model
		"""
		#debug
		print("GPT-model in use:")
		print(self.model)
		"""
		self.generation_kwargs = generation_kwargs

	@retry(wait=wait_random_exponential(min=1, max=60), stop=stop_after_attempt(6))
	def __call__(self, prompt):
		# Set the OpenAI API key
		openai.api_key = os.environ["OPENAI_API_KEY"]

		messages = [{"role": "user", "content": prompt}]
		
		if self.generation_kwargs is None:
			#print("(default generation parameters)") 
			completion = openai.chat.completions.create(
				model=self.model,
				messages=messages,
			)
		else:
			#print("(generation parameters from experiment setup)") 	
			completion = openai.chat.completions.create(
				model=self.model,
				messages=messages,
				temperature= self.generation_kwargs['temperature'],
				top_p= self.generation_kwargs['top_p'],
				max_completion_tokens= self.generation_kwargs['max_new_tokens'], 		
		)

		response= completion.choices[0].message.content
		
		return response

"""
class FastChatLLM:
	def __init__(self, model=None, tokenizer=None):
		self.model = model
		self.tokenizer = tokenizer

	def __call__(self, prompt):
		conv = get_conversation_template('vicuna-7b-1.5')
		conv.append_message(conv.roles[0], prompt)
		conv.append_message(conv.roles[1], None)
		input = conv.get_prompt()

		input_ids = self.tokenizer([input]).input_ids
		output_ids = self.model.generate(
			torch.as_tensor(input_ids).to(self.model.device),
			do_sample=True,
			temperature=0.1,
			max_new_tokens=1024,
		)

		output_ids = output_ids[0][len(input_ids[0]) :]
		response = self.tokenizer.decode(output_ids, skip_special_tokens=True).strip()
		return response
"""

class NShotLLM(object):
	def __init__(self, model, tokenizer, reward_model, args, generation_kwargs):
		self.model = model
		self.tokenizer = tokenizer
		self.reward_model = reward_model
		self.args = args
		self.generation_kwargs = generation_kwargs		
		self.device = next(self.model.parameters()).device
		self.max_len= args.cutoff_len+args.PREDICT_EXAMPLES_NUM_TOKENS if args.fewshots else args.cutoff_len
		
	def generate_and_tokenize_prompt(self, instruction):

		prompt = create_prompt(instruction, self.args.fewshots)
		
		# free tokenization. Checked 'a posteriori'
		tokenized = self.tokenizer(
			prompt,
			truncation= False,
			max_length= self.max_len, # to avoid default
			padding= True, 
			pad_to_multiple_of= self.args.pad_to_multiple_of, 
			return_tensors='pt',				
			)
		num_tokens= tokenized["input_ids"].shape[1]
		return prompt, tokenized, num_tokens
		
	def inference(self, batch):	
		print("\nPerforming inference:")
		response_tensors = generate_retry(self.model, self.tokenizer, batch, self.generation_kwargs)
		if response_tensors is None:
			print("No response was generated by the model at least one of the inputs. Let's pass to next batch of questions")
			return FAULT_ANSWER

		batch["response"] = [self.tokenizer.decode(response, skip_special_tokens=True) for response in response_tensors]
		
		print("Calculating rewards")
		texts = [query + response for query, response in zip(batch["query"], batch["response"])]
		logits = calculate_rewards(self.reward_model, 
			self.tokenizer, 
			tuple(texts), 
			self.args.padding, 
			max_len= self.args.cutoff_len if self.args.max_len_rm is None else min(self.args.cutoff_len, self.args.max_len_rm), # to conform to the answers in the data set
			pad_to_multiple_of= self.args.pad_to_multiple_of,
			)
		calculate_rewards.cache_clear() #to freed cpu cache
		reward_tensors = [torch.tensor(logit.item(), device=self.device) for logit in logits] 
		# debug
		print(reward_tensors)
		return reward_tensors, batch

	def __call__(self, instruction):
		
		query, tokenized, num_tokens= self.generate_and_tokenize_prompt(instruction)
		if num_tokens>self.max_len:
			print("Inputs are out of range. Return default answer")
			return FAULT_ANSWER
			
		batch = {
			'query': [query] * self.args.num_shots,
			'input_ids': [tokenized['input_ids']] * self.args.num_shots,  # repeat the same to have multiple answers
			'attention_mask': [tokenized['attention_mask']] * self.args.num_shots
		}
		
		max_retries=1#3
		
		for attempt in range(max_retries):
			reward_tensors, batch = self.inference(batch)
			values = torch.stack(reward_tensors).squeeze()
			idx = torch.argmax(values).item()
			best_reward = reward_tensors[idx].item()
			print("best reward:", str(best_reward))
			best_answer= batch["response"][idx].split("Price Movement:")[-1]
			if best_reward > self.args.reward_baseline:
				print("Returning worthy answer")
				return best_answer
			else:
				print( f"Retry {attempt + 1}/{max_retries} was unsatisfactory")
				continue

		print(f"Rewards resulted unsatisfactory after {max_retries} retries\n")
		return best_answer #FAULT_ANSWER

